// Original quiz wording. Scripture text is requested at runtime from the NET Bible service.
const QUESTIONS = [
 {verse:21,title:'A child named Jesus',little:[['What name was the baby given?','Jesus','Moses','David'],['Who would he save?','His people','The fish','The soldiers'],['What would he save his people from?','Their sins','The rain','The sea']],big:[['Who visited Joseph in a dream?','An angel','A shepherd','A king'],['What name was Joseph told to give Mary’s son?','Jesus','John','Peter'],['What does Immanuel mean?','God with us','A mighty king','A new city']]},
 {verse:10,title:'Visitors from the east',little:[['What did the visitors see?','A star','A kite','A boat'],['How did they feel?','Very joyful','Very angry','Very sleepy'],['What made them joyful?','Seeing the star','Finding a coin','Hearing a trumpet']],big:[['What guided the wise men?','A star','A cloud','A dove'],['Who wanted to find the child Jesus?','Herod','Pilate','Peter'],['Where did Joseph take Mary and Jesus to escape?','Egypt','Rome','Nazareth']]},
 {verse:17,title:'Jesus is baptized',little:[['Where did the voice come from?','Heaven','A boat','A house'],['Who did the voice call its Son?','Jesus','John','Peter'],['How did the voice describe him?','Beloved','Lost','Afraid']],big:[['Who baptized Jesus?','John the Baptist','Peter','Matthew'],['Which river is named in this chapter?','The Jordan','The Nile','The Tigris'],['What descended like a dove?','The Spirit of God','A star','A scroll']]},
 {verse:19,title:'Follow me',little:[['Who said “Follow me”?','Jesus','Herod','Joseph'],['What were the people invited to do?','Follow Jesus','Build a tower','Plant a tree'],['What kind of people would they fish for?','People','Soldiers','Kings']],big:[['What did Jesus refuse to turn stones into?','Bread','Fish','Gold'],['What work did Simon Peter and Andrew do?','Fishing','Farming','Carpentry'],['What did Jesus tell them they would fish for?','People','Coins','Birds']]},
 {verse:14,title:'Light for the world',little:[['What did Jesus call his followers?','The light of the world','The wind of the world','The sea of the world'],['What can be seen on a hill?','A city','A fish','A seed'],['Can a city on a hill be hidden?','No','Yes','Only at noon']],big:[['Who are called blessed in the Beatitudes?','The merciful','The proud','The cruel'],['What did Jesus call his followers?','The salt of the earth','The rulers of Rome','The oldest trees'],['Where should a lamp be placed?','On a lampstand','Under a basket','Inside a jar']]},
 {verse:9,title:'A way to pray',little:[['Who is the prayer addressed to?','Our Father','A king','A soldier'],['Where does the prayer say the Father is?','In heaven','In a boat','In a field'],['What should be honored?','His name','Our shoes','The city gate']],big:[['Where did Jesus say to store treasures?','In heaven','In a barn','In a palace'],['Which birds did Jesus point to as an example of God’s care?','Birds of the sky','Penguins','Peacocks'],['What prayer begins “Our Father in heaven”?','The Lord’s Prayer','A wedding prayer','A travel prayer']]},
 {verse:7,title:'Ask, seek, knock',little:[['What should you do to receive?','Ask','Hide','Run'],['What should you do to find?','Seek','Sleep','Shout'],['What should you do for a door to open?','Knock','Paint','Lock']],big:[['What should you do to find?','Seek','Hide','Wait silently'],['Which gate leads to life?','The narrow gate','The widest gate','The golden gate'],['What did the wise builder build on?','Rock','Sand','Leaves']]},
 {verse:26,title:'Jesus calms the storm',little:[['How did Jesus describe the disciples’ faith?','Little','Huge','Lost forever'],['What did Jesus calm?','The winds and the sea','A crowd in a market','A flock of sheep'],['What happened after Jesus spoke?','It became calm','The boat grew','The sun disappeared']],big:[['What did Jesus do for a person with leprosy?','He healed him','He sent him to sea','He gave him a coin'],['Whose servant did Jesus heal?','A centurion’s','A fisherman’s','A farmer’s'],['What did Jesus calm?','A storm','A market','A fire']]},
 {verse:2,title:'Take heart',little:[['What did Jesus tell the paralyzed man?','Take heart','Go fishing','Climb a tree'],['What did Jesus say was forgiven?','His sins','His house','His boat'],['Who spoke to the man?','Jesus','Herod','Pilate']],big:[['What was Matthew’s job before following Jesus?','Tax collector','Fisherman','Soldier'],['Who was brought to Jesus on a stretcher?','A paralyzed man','A shepherd','A king'],['Whose daughter did Jesus raise?','A synagogue leader’s','A centurion’s','A farmer’s']]},
 {verse:31,title:'You matter',little:[['What did Jesus say first?','Do not be afraid','Run away','Be quiet'],['What birds are mentioned?','Sparrows','Eagles','Doves'],['Are people worth more than many sparrows?','Yes','No','Only on Sundays']],big:[['How many apostles did Jesus send out?','Twelve','Three','Seventy'],['What birds did Jesus say are not forgotten by the Father?','Sparrows','Eagles','Owls'],['Who should the disciples tell others about?','Jesus','Herod','Caesar']]},
 {verse:28,title:'Come and rest',little:[['Who invites tired people to come?','Jesus','A king','A soldier'],['Who can come to Jesus?','Those who are weary','Only sailors','Only rulers'],['What does Jesus promise to give?','Rest','A crown','A boat']],big:[['Who sent messengers to ask about Jesus?','John the Baptist','Herod','Pilate'],['Whom did Jesus invite to come to him?','The weary and burdened','Only kings','Only fishermen'],['What did Jesus promise to give them?','Rest','Gold','A house']]},
 {verse:12,title:'Doing good',little:[['Which day is mentioned?','The Sabbath','A birthday','A feast day'],['What is lawful to do on that day?','Do good','Do harm','Hide from people'],['What kind of action does Jesus encourage?','Good','Mean','Careless']],big:[['What did the disciples pick on the Sabbath?','Heads of grain','Figs','Grapes'],['What did Jesus heal in the synagogue?','A man’s hand','A man’s foot','A man’s ear'],['Which prophet’s sign did Jesus mention?','Jonah’s','Isaiah’s','Moses’']]},
 {verse:31,title:'A tiny seed',little:[['What seed did Jesus mention?','A mustard seed','An apple seed','A rice seed'],['What did someone do with the seed?','Sowed it','Painted it','Threw it in water'],['Where was it planted?','In a field','On a roof','In a boat']],big:[['What fell on different kinds of ground?','Seed','Coins','Fish'],['What tiny seed did Jesus use in a parable?','Mustard seed','Apple seed','Rice seed'],['What did the merchant seek in another parable?','Fine pearls','Fine horses','Fine houses']]},
 {verse:19,title:'Sharing a meal',little:[['What food did Jesus take?','Bread and fish','Rice and fruit','Honey and milk'],['What did Jesus do before sharing it?','He gave thanks','He went to sleep','He hid it'],['Who received the food from Jesus?','The disciples','The soldiers','The rulers']],big:[['How many loaves were used to feed the crowd?','Five','Two','Twelve'],['What else was shared with the loaves?','Two fish','Two apples','Two jars of oil'],['Who walked toward Jesus on the water?','Peter','Matthew','John the Baptist']]},
 {verse:32,title:'Caring for the crowd',little:[['Who cared about the crowd?','Jesus','Herod','Pilate'],['How many days had the crowd stayed?','Three','One','Seven'],['Did Jesus want them to leave hungry?','No','Yes','Only the adults']],big:[['What did a Canaanite woman ask Jesus to do?','Help her daughter','Build a house','Find a coin'],['How many men were fed in the later meal?','Four thousand','Five hundred','Twelve'],['Why did Jesus care for the crowd?','They had stayed with him and had no food','They brought gifts','They built a boat']]},
 {verse:16,title:'Who is Jesus?',little:[['Who did Peter say Jesus is?','The Christ','A tax collector','A soldier'],['Whose Son did Peter call Jesus?','The living God’s','Herod’s','A fisherman’s'],['Who answered Jesus?','Simon Peter','Pilate','Matthew']],big:[['Who said Jesus is the Christ?','Simon Peter','Herod','Pilate'],['What did Jesus say he would build?','His church','A palace','A ship'],['What did Jesus tell his followers to take up?','Their cross','A sword','A crown']]},
 {verse:5,title:'Listen to him',little:[['What appeared around them?','A bright cloud','A dark cave','A tall tree'],['What did the voice say about Jesus?','He is my beloved Son','He is a stranger','He is a soldier'],['What did the voice say to do?','Listen to him','Run away','Build a boat']],big:[['Who appeared with Jesus at the transfiguration?','Moses and Elijah','Peter and Andrew','Herod and Pilate'],['What did the voice from the cloud say?','Listen to Jesus','Leave the mountain','Build a temple'],['Where did Peter find a coin for the tax?','In a fish’s mouth','Under a rock','In a tree']]},
 {verse:4,title:'Be humble',little:[['Who does Jesus use as an example?','A child','A king','A soldier'],['What quality does Jesus praise?','Humility','Pride','Anger'],['Who is greatest in heaven’s kingdom?','The one who becomes humble like a child','The strongest soldier','The richest king']],big:[['Whom did Jesus place among the disciples?','A child','A ruler','A soldier'],['What animal was lost in Jesus’ story?','A sheep','A camel','A dove'],['How did the servant in the final parable treat someone who owed him money?','He refused mercy','He forgave immediately','He gave him a gift']]},
 {verse:14,title:'Children are welcome',little:[['Who did Jesus invite to come?','Little children','Only soldiers','Only rulers'],['Did Jesus want people to stop them?','No','Yes','Only sometimes'],['Who spoke these words?','Jesus','Herod','Pilate']],big:[['Whom did Jesus welcome?','Little children','Only priests','Only rulers'],['What was the rich young man told to give away?','His possessions','His sandals','His boat'],['What did the young man want to know?','How to gain eternal life','How to sail','How to build a house']]},
 {verse:28,title:'Jesus came to serve',little:[['Did the Son of Man come to be served or to serve?','To serve','To be served','To hide'],['What did he give?','His life','A boat','A crown'],['For how many did he give it?','Many','Only one','Nobody']],big:[['Who worked different lengths of time but received the same wage?','Vineyard workers','Fishermen','Builders'],['What did Jesus say he came to do?','Serve','Rule by force','Hide'],['How many blind men called out to Jesus near Jericho?','Two','One','Twelve']]},
 {verse:9,title:'A king arrives',little:[['Who did the crowd praise?','The Son of David','A soldier','A merchant'],['What word did the crowd shout?','Hosanna','Goodbye','Silence'],['Where did the crowd say he came from?','In the name of the Lord','From a boat','From a cave']],big:[['What animal did Jesus ride into Jerusalem?','A donkey','A horse','A camel'],['What did Jesus drive out of the temple?','People buying and selling','People praying','People reading'],['What tree withered after Jesus spoke?','A fig tree','An olive tree','A cedar']]},
 {verse:37,title:'Love God',little:[['Whom should we love?','The Lord our God','Only ourselves','Only our friends'],['What part of us should love God?','Our heart','Only our hands','Only our feet'],['Should we love God with all or a little of our heart?','All','A little','None']],big:[['Whose image was on the tax coin?','Caesar’s','Peter’s','David’s'],['What is the greatest commandment?','Love God with all your heart','Build a tower','Collect many coins'],['What is the second commandment like it?','Love your neighbor as yourself','Work all night','Eat together']]},
 {verse:12,title:'Choose humility',little:[['What happens to someone who lifts themselves up proudly?','They will be humbled','They will fly','They will find treasure'],['What happens to someone who is humble?','They will be lifted up','They will be forgotten','They will be lost'],['Which quality is praised?','Humility','Pride','Greed']],big:[['Which teachers did Jesus warn about?','Scribes and Pharisees','Fishermen','Shepherds'],['What did Jesus say happens to the humble?','They will be exalted','They will be forgotten','They will be punished'],['What city did Jesus lament over?','Jerusalem','Rome','Bethlehem']]},
 {verse:42,title:'Stay ready',little:[['What did Jesus say to do?','Stay alert','Go to sleep','Hide'],['Do we know the exact day the Lord comes?','No','Yes','Only in summer'],['Who is expected to come?','The Lord','A merchant','A soldier']],big:[['What did Jesus say would happen to the temple stones?','They would be thrown down','They would turn to gold','They would float'],['What did Jesus say his followers should do?','Stay alert','Ignore the signs','Hide in the temple'],['Which tree did Jesus use as a lesson?','A fig tree','An apple tree','A cedar']]},
 {verse:21,title:'Well done!',little:[['What did the master say?','Well done','Go away','Be silent'],['How did he describe the servant?','Good and faithful','Lazy and angry','Lost and tired'],['What was the servant invited to share?','The master’s joy','A storm','A long trip']],big:[['How many bridesmaids were wise in the story?','Five','Two','Ten'],['What did the master entrust to servants?','Talents','Boats','Fish'],['What did the king call those who cared for the needy?','Blessed','Forgotten','Foolish']]},
 {verse:26,title:'Remember Jesus',little:[['What did Jesus take?','Bread','A coin','A stone'],['What did Jesus do before breaking it?','He gave thanks','He went to sleep','He ran away'],['Who received the bread?','The disciples','The soldiers','The crowds outside']],big:[['Who agreed to betray Jesus?','Judas','Peter','John'],['What did Jesus share with his disciples at supper?','Bread and a cup','Fish and a net','Coins and a scroll'],['Where did Jesus pray before his arrest?','Gethsemane','Bethlehem','Nazareth']]},
 {verse:54,title:'At the cross',little:[['What did the centurion say about Jesus?','He was the Son of God','He was a fisherman','He was a tax collector'],['Who spoke these words?','The centurion','A wise man','A shepherd'],['Was the centurion alone?','No, others were with him','Yes','The verse does not mention anyone']],big:[['Who handed Jesus over to be crucified?','Pilate','Peter','Joseph'],['Who helped carry Jesus’ cross?','Simon of Cyrene','John the Baptist','Matthew'],['Where was Jesus’ body placed?','In a tomb','In a boat','In the temple']]},
 {verse:6,title:'He is risen',little:[['Was Jesus still in the tomb?','No','Yes','The verse does not say'],['What happened to Jesus?','He was raised','He sailed away','He fell asleep'],['What did the messenger invite them to see?','The place where he lay','A new boat','A mountain path']],big:[['Who first heard the news at the tomb?','The women','The soldiers','The wise men'],['What was the news?','Jesus had been raised','Jesus had gone fishing','Jesus was in the temple'],['What did Jesus tell his followers to make?','Disciples of all nations','A large palace','A new boat']]}
];
const REWARDS = [
 ['Sunset suit','outfit','🧡'],['Golden trail','trail','✦'],['Explorer goggles','hat','🥽'],['Coin magnet','power','🧲'],['Sky-blue suit','outfit','💙'],['Cloud trail','trail','☁️'],['Adventure cap','hat','🧢'],['Shield start','power','🛡️'],['Forest suit','outfit','💚'],['Spark trail','trail','✨'],['Pilot helmet','hat','🪖'],['Double stars','power','🌟'],['Purple suit','outfit','💜'],['Rainbow trail','trail','🌈'],['Royal crown','hat','👑'],['Extra life','power','❤️'],['Golden suit','outfit','💛'],['Fire trail','trail','🔥'],['Star visor','hat','🕶️'],['Slow motion','power','⏳'],['Coral suit','outfit','🩷'],['Comet trail','trail','☄️'],['Winged hat','hat','🪽'],['Super magnet','power','🧲'],['Midnight suit','outfit','💙'],['Glitter trail','trail','💫'],['Hero helmet','hat','⚡'],['Radiant shield','power','🌞']
];
