// Conversation starters for parents: two questions per chapter to help kids reflect and get to know Jesus.
const PARENT_TALK = {
  1: ['God gave Jesus the name Immanuel, “God with us.” When is a time you want to remember that God is with you?', 'Joseph obeyed God even when it was hard. What is something hard God might be asking our family to do?'],
  2: ['The wise men traveled a long way to worship Jesus. What can we do this week to make time for Jesus?', 'God protected Jesus’ family. How has God taken care of our family?'],
  3: ['God said, “This is my Son, whom I love.” How does it feel to know God loves you like that too?', 'John told people to turn back to God. Is there anything you want to say sorry to God for today?'],
  4: ['Jesus used God’s words to say no to temptation. Which Bible verse could help you when you’re tempted?', 'Jesus asked the fishermen to follow him, and they did right away. What does following Jesus look like at school or at home?'],
  5: ['Jesus said we are the light of the world. Who is someone you could shine for this week?', 'Jesus said to love our enemies. Is there someone who is hard to love? How could we pray for them?'],
  6: ['Jesus taught us to pray “Our Father.” What would you like to talk to God about today?', 'Jesus said not to worry, because God takes care of the birds. What are you worried about that we can give to God?'],
  7: ['Jesus said, “Ask, seek, knock.” What is something you want to ask God for?', 'The wise man built on the rock by doing what Jesus said. What is one thing Jesus said that we can do this week?'],
  8: ['Jesus calmed a big storm. What feels like a storm in your life right now?', 'Jesus touched and healed people others stayed away from. Who could you be kind to that others leave out?'],
  9: ['Jesus called Matthew, a tax collector people didn’t like. Why do you think Jesus wanted to be his friend?', 'Jesus said he came for people who need him. How do you need Jesus today?'],
  10: ['Jesus said you are worth more than many sparrows. What does that tell you about how God sees you?', 'Jesus sent his friends to tell others about him. Who could you tell about Jesus?'],
  11: ['Jesus said, “Come to me, all who are tired, and I will give you rest.” When do you feel tired or stressed?', 'How can we find rest with Jesus as a family?'],
  12: ['Jesus healed a man on the Sabbath because doing good matters. What good thing could you do for someone this week?', 'Jesus said our words show what is in our hearts. What kind words could you say tomorrow?'],
  13: ['In the story of the seeds, which kind of soil do you want your heart to be like? Why?', 'Jesus said the kingdom is like a tiny mustard seed that grows big. What small thing could God grow in you?'],
  14: ['Jesus fed thousands with five loaves and two fish. What little thing could you give to Jesus?', 'Peter sank when he looked at the wind. What helps you keep your eyes on Jesus?'],
  15: ['A mom kept asking Jesus to help her daughter. Why do you think Jesus loved her faith?', 'Jesus said what comes out of our mouths shows our hearts. How was your heart today?'],
  16: ['Jesus asked, “Who do you say I am?” Who is Jesus to you?', 'Peter said Jesus is the Christ, the Son of God. What do you want to know more about Jesus?'],
  17: ['God said, “Listen to him.” How can we listen to Jesus every day?', 'Jesus said faith as small as a mustard seed can do big things. What do you want to trust God with?'],
  18: ['Jesus said to become humble like a child. What do you think being humble means?', 'Jesus said to forgive again and again. Is there someone you need to forgive?'],
  19: ['Jesus welcomed the children. How does it feel to know Jesus always has time for you?', 'The rich young man found it hard to give up his things. Is there anything you love more than Jesus?'],
  20: ['Jesus came to serve, not to be served. How can you serve someone in our family this week?', 'Two blind men asked Jesus for help, and he had compassion on them. What do you want Jesus to help you see?'],
  21: ['The crowd shouted “Hosanna!” to praise Jesus. What are you thankful to Jesus for today?', 'Jesus was upset when people misused God’s house. How can we show respect for God?'],
  22: ['Jesus said the greatest commandment is to love God with all your heart. What does loving God with all your heart look like?', 'Who is a neighbor you could show love to this week?'],
  23: ['Jesus said the greatest among you will be a servant. Who is someone you think serves others well?', 'Jesus wants us to be the same on the inside as on the outside. Why does that matter?'],
  24: ['Jesus said to stay awake and be ready for his return. How can we live ready for Jesus?', 'Jesus said his words will never pass away. Why can we trust what Jesus says?'],
  25: ['When we help someone in need, Jesus says we do it for him. Who could we help together?', 'The servants used what the master gave them. What gifts has God given you to use?'],
  26: ['Jesus shared bread and wine with his friends to remember him. What do you want to remember about Jesus?', 'Peter said he didn’t know Jesus, but Jesus still loved him. How does it feel to know Jesus forgives us?'],
  27: ['Jesus died on the cross because he loves us. How does that make you feel?', 'The soldier said, “Truly this was God’s Son.” What do you believe about Jesus?'],
  28: ['Jesus is alive! Why is that such good news?', 'Jesus said, “I am with you always.” How can we remember that this week?']
};
