// Bonus reflection questions — a free extra every 3rd chapter (and in the home-upgrade quiz).
// Key = the chapter that triggers it. Row: [prompt, best answer, other, other]. Wrong answers never block anything.
const REFLECT = {
  3: { title: 'Jesus is born, the wise men, the baptism',
       big: ['Jesus is called “Immanuel,” which means “God with us.” What does that tell you about God?', 'God wants to be close to us', 'God lives far away', 'God only visits on holidays'],
       little: ['Who came to be with us?', 'Jesus', 'A king from far away', 'A big angel'] },
  6: { title: 'Temptation, salt and light, how to pray',
       big: ['When Jesus was tempted, he answered with words from Scripture. What can you do when you’re tempted to do wrong?', 'Remember what God says and choose to obey, even when no one is looking', 'Do it if nobody is watching', 'Just hope it goes away'],
       little: ['Jesus said we are a light. How can you shine?', 'Be kind to others', 'Hide under a blanket', 'Turn off the lights'] },
  9: { title: 'The wise builder, the storm, Matthew is called',
       big: ['The wise builder heard Jesus’ words and did them. What makes your life strong like a house on a rock?', 'Doing what Jesus says, not just hearing it', 'Knowing lots of Bible facts', 'Having a really big house'],
       little: ['The disciples were scared in the storm. What can you do when you’re scared?', 'Talk to Jesus', 'Run away', 'Cry and never stop'] },
  12: { title: 'Sparrows, “Come to me,” doing good',
       big: ['Jesus said God cares even about sparrows, and you are worth more than many sparrows. How should that change the way you see yourself?', 'I matter to God, even when I feel small and make mistakes', 'Only important people matter to God', 'God is too busy to notice me'],
       little: ['Does God care about you?', 'Yes, so much!', 'Only sometimes', 'Only when I’m good'] },
  15: { title: 'Seeds and soil, walking on water',
       big: ['Peter began to sink when he looked at the wind instead of Jesus. What “wind” can take your eyes off Jesus?', 'Worries and fears that feel big', 'Reading your Bible', 'Praying with your family'],
       little: ['Jesus fed lots of people with a little food. What can you share?', 'My snack or my toys', 'Nothing, it’s all mine', 'Only things I don’t like'] },
  18: { title: 'Peter’s answer, humble like a child, forgiving',
       big: ['Jesus said to forgive “seventy times seven.” What does that mean for someone who keeps hurting you?', 'Keep forgiving, and ask a grown-up for help if you need it', 'Forgive once, then never again', 'Pretend it didn’t happen'],
       little: ['What do we do when a friend says sorry?', 'Forgive them', 'Stay mad', 'Tell everyone'] },
  21: { title: 'Children welcome, came to serve, Jesus enters Jerusalem',
       big: ['Jesus came “not to be served but to serve.” What’s one way to live like that this week?', 'Help someone without being asked', 'Wait for others to help me first', 'Only help if I get a reward'],
       little: ['Jesus said, “Let the children come to me.” Can you talk to Jesus?', 'Yes, anytime!', 'Only grown-ups can', 'Only at church'] },
  24: { title: 'The greatest commandment, being ready',
       big: ['Jesus said the greatest commandment is to love God with all your heart, soul and mind, and to love your neighbor as yourself. Which shows that kind of love?', 'Being kind to the kid nobody plays with', 'Being nice only to my best friends', 'Saying I love God but being mean'],
       little: ['Jesus wants us to love others. How can you show love to someone today?', 'Help them or give them a hug', 'Take their toy', 'Not talk to them'] },
  27: { title: 'Helping “the least of these,” the Last Supper, the cross',
       big: ['Jesus said when we help someone hungry, lonely or sick, we are doing it for him. Who could you help like that?', 'Someone who is sad, left out or in need', 'Only people who can pay me back', 'Nobody, that’s a grown-up’s job'],
       little: ['Jesus died on the cross because he loves us. How much does Jesus love you?', 'More than anything!', 'A tiny bit', 'Only on good days'] },
  28: { title: 'He is risen!', finale: true,
       big: ['Jesus told his followers to go and tell others about him. Who could you tell about Jesus?', 'A friend or family member', 'No one, it’s a secret', 'Only people who already know'],
       bigType: 'Name them and type it in!',
       bigDone: 'Great! Try to go to them this week and share with them about Jesus.',
       little: ['Is Jesus alive?', 'Yes, he is risen!', 'No', 'I don’t know'] }
};
